apiVersion: infrastructure.eksctl.io/v1alpha5
kind: EKSCluster
metadata:
  name: staging-cluster # set the AWS cluster name here
spec:
  region: us-east-1 # set the AWS region here
  cloudWatch:
    clusterLogging:
      enableTypes:
      - audit
      - authenticator
      - controllerManager
  iam:
    serviceAccounts:
    - attachPolicyARNs:
      # FIXME: https://github.com/weaveworks/wk-quickstart-eks/issues/56 "Default cluster-config.js creates a ServiceAccount with AWS AdministratorAccess"
      - arn:aws:iam::aws:policy/AdministratorAccess
      metadata:
        name: ekscontroller
        namespace: wkp-eks-controller
    withOIDC: true
  nodeGroups:
  - desiredCapacity: 3
    iam:
      withAddonPolicies:
        albIngress: true
    instanceType: m5.large
    name: ng-0
  managedNodeGroupFile: 
  version: '1.18'
