apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgDLdiNGiMX+tqSeT3FtHxluz5rTJGdAtjV2r9LAY4pBB+lHKeNM9bF9ZgZMoS83h+6wUaL5UpZatKojsXfYHIb+ZDf++yXwbGwG20tfEzOwtft4PUiecLK0HmLTcXwZHLGQPlZ3QTyodrEErIVQ6MZproACuZf5xpIP/FHSiDT/rxg2DOC8M4xnHt+QkMnohtCje5IuhjZXQD5mIQ3/PPf0ErLvKOTCUClfdey9HWaBfUux6JOUf5x/Yc0nK9+Cqh4VDidJGeuADT7synC2pcBKsFssJhyVKvR87kXcFczVX6SHCWrVRdvt2+ZRdXIffx6iVKdCRx0XCwVX5Z/YFqqe3AIx7AHjPW2w3iHQgQ+L4Ds2N9ANdsFyrMeeHbVHBT79K5nAlTnfELBagPGLZtuNXTjQYUo35etexiAuFl+XAV+RDAAvnEOvU8/cEvcJ2SGZjx+OMFXYeutBAJ5hNlHFguDsmu2Nt0+PigscJD0Wvh/cfcSdixJyq6VEgYjd4c4WdjaH/Nug1wDKSCKhfMiZRfOrRrW8qmS3NnoDkXQDRwc3jQpintQFMUjgHTMLLH3r+QZTDASu3i7PzMtxLkktzJLxISGRvJKPG878b3C/zYnevnMvzbqUL6QUI8hUSU2AIWOMdnBhs1CT06tlrIhDMuvgW0rnO7JpUNVwkM3mlvLI8IUrkvag36O/ZBdCtLW9qKAXoBrY1dM=
    username: AgBRcNXY46A3NneiTUfTPWbgSUw+Metz5G9Bwur1xoQljBdIs8XQTnOFYIcaDqNX3ccwzzvMCD2stKd1RgN3kNF5uFQc0GCBHere4WqTOZuCzzZQ5wrMKSwA4+aQUiITHeCO0jEJCNEmOZbgZ3hsiEBzOdPSO+GSQ54av9u9KqufR5T9U/LKWXTdtXeNiFvoYJxUpLSfZquQ5Jtyl4yzkT7uEA5EBdIznxc9ELbC0D7hSTG9JSPx8PG04E7OVYVebshLA/CRWiy6MsziV9I0RK88zuWVdtVwwYB8qd+s2yvIUbxyF2ThtChjDTtQa6hTSu1GMmsglTayW0qicaRwb5auESwNnnzLZa09kmWvsGRcKEN7QQOIcSEYVEVadwLt0dGB7JLigg5jACRf4XjE/4LAaHRmmjHsGOBSUr5NM16bSzSpyUnbFEvB7shBiithNTCiQGIPM8PCQQcDOQ0aVMs9K98ZOaeZsWk3g2N3So1/Efp1XgTcgIawKqZvS0qR9KJ+i8bpJ/Umb+7ByZGy4uayRrIH2rE0JEvDAoYIN3Nm0DNqanoa5sUGwCaNCnPSVe9tg2vgg84zL9jfixTyG+VydnHlThgekOO4D9Yb/hNPx/9/IRt3fXAjBesMMuTk8MPlKsA47RA+HIZuma6TeRbw6Fbjchf2l4GS1uqGn0pQzgeklHeCBU/kwQ3MI9veyXg/2hGeDmVwyoc=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

